name: Analyze Real Project Code

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ai-agent .

      - name: Run Docker container
        run: docker run -d --name ai-agent -p 8010:8010 ai-agent

      - name: Wait for service readiness
        shell: bash
        run: |
          set -e
          for i in {1..30}; do
            if curl -sS http://localhost:8010/ -o /dev/null; then
              echo "Service is up"
              exit 0
            fi
            sleep 1
          done
          echo "Service not ready in time"
          docker logs ai-agent || true
          exit 1

      - name: Prepare real repo zip (subdirectory)
        shell: bash
        run: |
          set -e
          TARGET_DIR="test_repo"   
          test -d "$TARGET_DIR"
          cd "$TARGET_DIR"
          zip -r ../repo.zip . -x ".git/*" "__pycache__/*" "*.pyc" ".venv/*" ".idea/*" ".github/*"
          cd ..
          ls -lh repo.zip

      - name: Call API to analyze code
        shell: bash
        run: |
          set -e
          code=$(
            curl -sS -w "%{http_code}" -o result.json \
              -X POST "http://localhost:8010/analyze" \
              -F "problem_description=建立频道；在频道中传送消息；按时间倒序列出频道中的消息；打印信息" \
              -F "code_zip=@repo.zip"
          )
          echo "HTTP_STATUS=$code"
          test "$code" = "200"

      - name: Show container logs (always)
        if: always()
        run: docker logs ai-agent

      - name: Display analysis result (always)
        if: always()
        run: cat result.json || true

      - name: Upload analysis result (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: analyze-result
          path: result.json
