name: Analyze Real Project Code

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ai-agent .

      - name: Run Docker container
        run: docker run -d --name ai-agent -p 8010:8010 ai-agent

      - name: Prepare real repo zip
        run: |
          echo "Packing repository source code"
          zip -r repo.zip . -x ".git/*" ".venv/*" ".github/*" "__pycache__/*" "*.pyc" ".idea/*"
          ls -lh repo.zip

      - name: Call API to analyze code
        run: |
          set -e
          echo "Waiting for container to start"
          sleep 5
          echo "Calling /analyze endpoint for real project"
          code=$(
            curl -sS -w "%{http_code}" -o result.json \
              -X POST "http://localhost:8010/analyze" \
              -F "problem_description=建立频道；在频道中传送消息；按时间倒序列出频道中的消息；打印信息" \
              -F "code_zip=@repo.zip"
          )
          echo "HTTP_STATUS=$code"
          test "$code" = "200"

      - name: Show container logs
        run: docker logs ai-agent

      - name: Display analysis result
        run: cat result.json

      - name: Upload analysis result
        uses: actions/upload-artifact@v4
        with:
          name: analyze-result
          path: result.json
